Feature #18 - Define and execute refactoring plan for BibEntry::getSourceField
DD2480-gr25/jabref pull request #33
Opened 2022-02-25 13:04 UTC by emiros98

closes #18

2022-02-26 22:47 UTC, pat672 commented
Looks like this branch needs to resolve a conflict in the readme file @emiros98

2022-02-27 12:10 UTC, emiros98 commented
Resolved! @pat672

2022-02-27 23:22 UTC, pat672 requested changes
LGTM, just one small comment!

2022-02-27 23:22 UTC, pat672 commented on dd2480/README.md
> +
Could we also document the outcome of the refactoring for FieldNameLabel? Write down what CCN we started with and the reduction after refactoring

2022-02-27 23:49 UTC, emiros98 commented
All should be good now

2022-02-28 14:37 UTC, pat672 approved these changes
LGTM

2022-02-28 14:37 UTC, merged